#
# To run:
# docker-compose up -d --build
#
# To destroy:
# docker-compose down
#
version: "2"
services:
  json-server:
    build: ./json-server/
    image: json-server:0.1.0
    ports:
      - "3000:3000"
    container_name: json-server

  front-end:
    build: 
      context: ./front-end/
      args:
        BUILD_ENV: build-prod
    image: front-end:0.1.0
    links:
      - json-server
    ports:
      - "4500:80"
    container_name: front-end