#
# To run:
# docker-compose up -d --build
#
# To destroy:
# docker-compose down
#
version: "2"
services:
  json-server:
    build: ./json-server/
    image: json-server:1.0.0
    ports:
      - "3000:3000"
    container_name: json-server

  todo-frontend:
    build: 
      context: ./todo-frontend/
      args:
        BUILD_ENV: build-prod
    image: todo-frontend:1.0.0
    links:
      - json-server
    ports:
      - "4500:80"
    container_name: todo-frontend